---
- name: Install pre-requisites tools - java, net-tools, unzip, maven, docker, sonarscanner, trivy, sonarqube
  hosts: all
  become: true
  tasks:
    - name: Install java, net-tools, unzip & maven
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - openjdk-17-jdk
        - net-tools
        - unzip
        - maven

    - name: Download docker universal script
      get_url:
        url: https://get.docker.com
        dest: /tmp/docker.sh
        mode: 0755

    - name: Execute installation script
      shell:
        cmd: sh /tmp/docker.sh
      args:
        executable: /bin/bash

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start and enable docker service
      systemd:
        name: docker
        state: restarted
        enabled: true

    - name: Verify Docker works for ubuntu user
      command: docker --version
      become: yes
      become_user: ubuntu
    
    - name: Install dependencies for trivy
      apt:
        name: "{{ item }}"
        state: present
      with_items:
      - wget
      - apt-transport-https 
      - gnupg
      - lsb-release
    
    - name: Adding trivy public key
      shell:
        cmd: wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
    
    - name: Adding trivy repository
      shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list

    - name: Installing trivy
      apt:
        name: trivy
        state: present
        update_cache: yes

    - name: Download sonarscanner
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889-linux-x64.zip
        dest: /tmp/sonar-scanner-cli-7.1.0.4889-linux-x64.zip

    - name: Unzip sonarscanner
      unarchive:
        src: /tmp/sonar-scanner-cli-7.1.0.4889-linux-x64.zip
        dest: /home/ubuntu/
        remote_src: yes
        creates: /home/ubuntu/sonar-scanner-4.8.0.2856-linux

    - name: Run sonarqube container
      shell:
        cmd: docker run -d --name sonarqube -p 9000:9000 sonarqube:lts-community

